/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chessgame;

import org.junit.Test;
import static org.junit.Assert.*;

/**
 * Class that tests App class
 */
public class AppTest {

    /**
     * Method that providing a test
     */
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull("app should have a greeting", classUnderTest.run());
    }
}
